default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-stupid-coaching_development

test:
  <<: *default
  database: rails-stupid-coaching_test

production:
  <<: *default
  database: rails-stupid-coaching_production
  username: rails-stupid-coaching
